apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/ping-pong
  newTag: df8ebb6fffe25a951ccd8aac77b0998ff67a34a6