apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- cronjob.yaml
- analysistemplate.yaml
- secret.enc.yaml
bases:
  - "../client"
  - "../server"
  - "../persistent"
  # - "../broadcaster"