version: "3.4"

services:
  app:
    env_file:
      - project.env
      - .env
    build: app
    image: app
    restart: "no"
    #restart: "yes"
    #volumes:
      #- ./app/:/app
      #- ./app-cache/:/app-cache
    ports:
      #- 9999:9999
      - ${PORT:?err}:${PORT:?err}
      #- $PORT:$PORT
      #- ${PORT:-6666}:${PORT:-6666}
      #- 6666:6666
      #- 7777:7777
      #- 7788:7788
  #   depends_on:
  #     - database
  #     - flyway

  # database:
  #   container_name: database-server
  #   image: postgres:14.1
  #   restart: "no"
  #   env_file:
  #       - project.env

  # flyway:
  #   image: flyway/flyway:8.4.0-alpine
  #   depends_on:
  #     - database
  #   volumes:
  #     - .:/flyway/sql
  #   command: -connectRetries=60 -baselineOnMigrate=true migrate
  #   env_file:
  #     - project.env