apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: ping-pong
          image: rvlq/ping-pong:0946
          volumeMounts:
          - name: shared-image
            mountPath: /app/shared
          resources:
              limits:
                memory: "64Mi"
                cpu: "100m"