apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/ping-pong
  newTag: b09ad3ce0b662b20dfe5457be181679058ce9ce1
