version: "3.4"

services:
  app:
    env_file:
      - project.env
      - .env
    build: app
    image: ping-pong
    restart: "no"
    volumes:
      - ./app/:/app
      - ./app-cache/:/app-cache
    ports:
      # - ${PORT:?err}:${PORT:?err}
      - 8888:8888
  #     #- $PORT:$PORT
  #     #- ${PORT:-6666}:${PORT:-6666}
  #     #- 6666:6666
  #     #- 7777:7777
  #     #- 7788:7788
  #   depends_on:
  #     - database
  #     - flyway

  # database:
  #   container_name: database-server
  #   image: postgres:14.1
  #   restart: "no"
  #   env_file:
  #       - project.env
  #   #ports:
  #   #  - 5432:5432

  # flyway:
  #   image: flyway/flyway:8.4.0-alpine
  #   depends_on:
  #     - database
  #   volumes:
  #     - .:/flyway/sql
  #   command: -connectRetries=60 -baselineOnMigrate=true migrate
  #   env_file:
  #     - project.env
