apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todo
  namespace: project
spec:
  # schedule: "* * * * *"
  # schedule: "*/10 * * * *"
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            # image: rvlq/daily-job:latest
            imagePullPolicy: Always
            image: rvlq/daily-job:2.09
            # imagePullPolicy: IfNotPresent
            # command:
            # echo `curl -v https://en.wikipedia.org/wiki/Special:Random 2>&1 >/dev/null | grep '< location: '|cut -c13-153`
          restartPolicy: OnFailure
