apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj01-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj01
  template:
    metadata:
      labels:
        app: proj01
    spec:
      containers:
        - name: proj01
          image: rvlq/project:v0.2
