apiVersion: v1
kind: Service
metadata:
  name: proj01-svc
spec:
  type: NodePort
  selector:
    app: proj01 # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 31337 # This is the port that is available outside. Value for nodePort can be between 30000-32767
      protocol: TCP
      port: 1234 # This is a port that is available to the cluster, in this case it can be ~ anything
      targetPort: 9999 # This is the target port