apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj01-dep
  namespace: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proj01
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: proj01
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: pg-secrets
        image: IMAGE_PLACEHOLDER
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 9999
          initialDelaySeconds: 20
          periodSeconds: 10
          terminationGracePeriodSeconds: 60
        name: proj01
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9999
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /app/images
          name: shared-share
      volumes:
      - name: shared-share
        persistentVolumeClaim:
          claimName: share-claim
---
