apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-pong
spec:
  template:
    metadata:
      name: ping-pong-dwk-v0 # v0
    spec:
      containers:
        - image: IMAGE_PLACEHOLDER
          # environment
          envFrom:
            - secretRef:
                name: pg-secrets
