apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pg-statefulset.yaml
- secret.yaml
- pg-service.yaml
- knative-service.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/ping-pong
  newTag: e843eca8ec88d11d11078fa3271835e7a65fa365
