apiVersion: v1
kind: Secret
metadata:
    name: pg-secrets
    namespace: exercises
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Wi2t/YqF7fHybvRld/9JcykF91SK0MoqvHleCUh4dKQ=,iv:U2G3vO7MUKdP1HZ0lVAly2tPkhlY3koQ4/D+6u1yR3c=,tag:p4ZSMykByZi/cv+90Yp/uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6tag33d7xfm0uvuk4ey35ykz9afxwkjeszz843uts4ycmah9amqpl0vhr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWWdBbURrWGFINVRsVmhD
            WGxPc050bFVDcjA5bjFzTWRSYUJFNU1BUzFrCkMyVmFSa20zYmgya29nWWlCSTFF
            K2F6QStBbnVPZnZyMUFkaXN4Y253UEEKLS0tIEFvQVJ4bzUzK1ozZW92RjZhZDh0
            bFV6RDZIaUJ0eXR0YjVLRWFrVXlSd1kK3jmEfhYFnsKbe00Q3D2K5ww9BPuDSU6E
            8K5A8K/0XmsdEkB0Wyl2Jsiiva4K1XcYI4WNqPHM/dS8uW6kCSyIpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-02T14:43:52Z"
    mac: ENC[AES256_GCM,data:T4jg0up7ZePtejtuAwJaHZRD3wDFG/XEaK6JjMd3/3rzVPf0DXBDvj6NCTdDpt8Acv73snVFZKR3ZlXsGekvDsi1/lr74qB2kIL4AYCNmGJHWOnHqat1PZjk90LBxEwn0a5BztYqShJQ191CZM7FHx8l5JdllxgccU7bUy/IE/I=,iv:Q456yRivnLi8JFxkytW5052iSCaybGUCuu4kj6BAxSs=,tag:hQaA0/QJ5sY6/C7lkXqYVA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
