apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-claim
  namespace: project
spec:
  storageClassName: man-proj
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi