apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/ping-pong
  newTag: c10af5444c5c8849d61e2a89c21735995d438830
