apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - pg-statefulset.yaml
- pg-service.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/ping-pong
  newTag: 290fb007f8ee16bd14ad588ba4cfe0a1d984b53e
