version: "3.4"

services:
  app:
    env_file:
      - project.env
      - .env
    build:
      context: server/app
      dockerfile: Dockerfile_dev
    image: app
    restart: "no"
    volumes:
      - ./server/app/:/app
      - ./server/app-cache/:/app-cache
    ports:
      - ${PORT:?err}:${PORT:?err}
      #- 5432:5432
      #- $PORT:$PORT
      #- ${PORT:-6666}:${PORT:-6666}
      #- 6666:6666
      #- 7777:7777
      #- 7788:7788
    depends_on:
      - database
      - flyway

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env
    #ports:
    #  - 5432:5432

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - ./server:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
