apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- f-deployment.yaml
- f-service.yaml
- f-ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/proj-front
  newTag: e458e1b723ae98aee1a761c6a141904a1796d1f8
