name: Release Project broadcaster

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'Project/broadcaster/**'  
      - '.github/workflows/broadcaster.yaml' #

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          repository: rvlq/broadcaster
          path: Project/broadcaster
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: setup-build-publish

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: Project/manifests/broadcaster
      run: |-
        kustomize edit set image IMAGE_PLACEHOLDER=rvlq/broadcaster:${{ github.sha }}
    # Commit and push
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'Project/manifests/broadcaster/kustomization.yaml'
        message: New version release for project broadcaster ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.HUBGIT_TOKEN }}
    #