apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - f-deployment.yaml
resources:
- f-rollout.yaml
- f-service.yaml
- f-ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/proj-front
  newTag: f4146ba282fd294ef49aba3149e41246173456ca
