apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proj01-dep
  name: proj01-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj01-dep
  strategy: {}
  template:
    metadata:
      labels:
        app: proj01-dep
    spec:
      containers:
      - image: rvlq/project:v0.2
        name: project
        resources: {}
        # imagePullPolicy: Always
status: {}
