apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj02-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj02
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: proj02
    spec:
      containers:
      - image: IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        name: proj02
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
---
