apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- b-deployment.yaml
- b-service.yaml
- b-ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/project
  newTag: dbabd40b23f231669f19ee09a42bc9b700bfb56b
