apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - b-deployment.yaml
resources:
- b-rollout.yaml
- b-service.yaml
- b-ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/project
  newTag: 6795730feb72b56cf69e67a1da82603cf64d73e8
