apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - b-rollout.yaml
resources:
- b-deployment.yaml
- b-service.yaml
- b-ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/project
  newTag: b381da20df6e16dc20ba978990e1fbefb2980bd8
