apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - b-deployment.yaml
resources:
- b-rollout.yaml
- b-service.yaml
- b-ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/project
  newTag: 4d9f3c2bf758936fa84190ed02c1c475694f2390
