apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- f-deployment.yaml
# - f-rollout.yaml
- f-service.yaml
- f-ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: rvlq/proj-front
  newTag: e41955764e3aebc451424b13e3c44f59820b7e67
