apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: telegram-bot-token
data:
    TOKEN: ENC[AES256_GCM,data:+PRqDN3filcoys6ekfg86Ygi2/pKjJWEwUR+1F7iCIutKnnTZ0s37eBP4mLoi2bsq25KsfJVsSQQgS/jaJujhw==,iv:KA+WGyHpBvRvKhzSbsoRbKvuXbSiUaIwfRmZ4VqMggU=,tag:l9PhyBOaZCulw+Niettgrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6tag33d7xfm0uvuk4ey35ykz9afxwkjeszz843uts4ycmah9amqpl0vhr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa29PcStVWkVVeVVKcTc2
            OFI0N0JWRWNyK3hrTmV5d1FoN1lqSGRhSkRrCjIwVXF2NmxvZDdkaW53YVE2VGJt
            QWdjV1daZmJYZ3AzeVhTRmp5T0NkTmsKLS0tIHJ0VHNzS2xNaTRzcEZuWkZiN0t1
            T1o4eEFNZzBNV0lzdnhMd1NKby9pU0UKzIMPf0lsqs3frME+deg4HPG0DqS5egF9
            u4eqMsKyyVF2NzeBnY+0O38tC8KscYzAnOpRau6+Cup/1HZKQzs86w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T10:22:47Z"
    mac: ENC[AES256_GCM,data:sd+g/ldsy2q7VINZEEm9y8HXI4GBsqG7Eq+noONWshSxaq1+wUwIgdySEZuXBo+Ym6oVOlreGgiPEGDzDcwmJu+IHsUEj23b3AsJF+3ykBvgVqHJS8sOHHnTYv/FhaLKTnLutgHxdLAfHuZne8roOrZ1FROqSMeVDSqQNbB7zWU=,iv:/w+2DjdxUOQRL2h78xi583ivA4n4gTdF0hhQjiISGtI=,tag:ANl6Et7FtSOIWQ4U6Goq8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
