name: Release application

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'log-pong/ping-pong/app/**'  
      - '.github/workflows/ping.yaml' #

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # # Build the Docker image
      # - name: Build
      #   run: |-
      #     docker build ./Project/client \
      #       --tag "gcr.io/$PROJECT_ID/$IMAGE-front:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      #     docker build ./Project/daily-todos \
      #       --tag "gcr.io/$PROJECT_ID/$IMAGE-cron:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      #     docker build ./Project/server/app \
      #       --tag "gcr.io/$PROJECT_ID/$IMAGE-back:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      # # Push the Docker image to Google Container Registry
      # - name: Publish
      #   run: |-
      #     docker push "gcr.io/$PROJECT_ID/$IMAGE-front:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      #     docker push "gcr.io/$PROJECT_ID/$IMAGE-back:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      #     docker push "gcr.io/$PROJECT_ID/$IMAGE-cron:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      # - name: Login to Docker Hub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          repository: rvlq/ping-pong
          path: log-pong/ping-pong/app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: setup-build-publish

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: log-pong/ping-pong/manifests
      run: |-
        kustomize edit set image IMAGE_PLACEHOLDER=rvlq/ping-pong:${{ github.sha }}
    # Commit and push
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'log-pong/ping-pong/manifests/kustomization.yaml'
        message: New version release for ping-pong ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.HUBGIT_TOKEN }}
    # action trigger edit