apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: log-output # This is the app as declared in the deployment.
  ports:
    - port: 80
      protocol: TCP
      targetPort: 7777
